### ISSUE TITLE
Rewrite wizard

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#1473]
Wizard framework should be written in a more modular and extensible way. 

**Considered approach:**
- [x] Investigate other wizard frameworks (pros and cons)
- [x] Establish the requirements and functionalities our wizard should have
- [x] Prepare the concept framework
- [x] Rewrite existing wizard (step by step if possible)
