### ISSUE TITLE
Dark theme follow up

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1929]
### Dark theme
* [x] Cards `#202021`
* [x] Lines `#464647`
* [x] Background `#000000`
* [x] Hover Row `#2D2D2E`

both modal and dropdowns should be a bit lighter otherwise they blend into the background too much
* [x] Modal Background `#2b2b2c`
* [x] Dropdowns (e. g. on Cluster): Background `#2b2b2c` and Hover `#535354`

### Light theme & dark theme
* [x] Primary Blue `#00A3D9` -> hover `#4DC3EA`
* [x] Secondary Green `#00CCA7` -> hover `#67DAB9`
* [x] Adjust primary-dark and secondary-dark color see comment below

### Light theme
* [x] Can we make the border on buttons like delete on cluster overview darker? I know it's linked to the lines rn which is fine on dark theme but on light theme it's almost not visible, I can't think of another color to link it to though
