### ISSUE TITLE
UI/UX Fixes + more Dark Theme Follow Up

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#1967]
Dark Theme follow up II
- [x] cluster create random name icon should be white
- [x] OpenShift logo in switcher should be white when deactivated
- [x] Change info icon to white on the i and `#464647` line-grey on the background circle
- [x] Make the V of the KubeVirt logo black
- [x] make the steering wheel of kubeAdm black
- [x] Make the squares and their outlines black on the vmsware vsphere logo
- [x] please change it back so that ticked boxes have a white tick inside (sorry)
- [x] Interface flashes white on reload, can that be fixed?

Other stuff
- [x] decrease max height and min height of provider logos to 24px (at least that's what my experiment resulted in when I wanted to make aws/azure smaller)
- [x] left align Provider Logos in Cluster Overview
- [x] Change Account to Account Settings or User Settings, preference? 
- [x] Give Kubernetes/Openshift switcher same height as form fields/align them (optically increase margin-top to 4px and make max height 56px)
- [x] Can we make provider and datacenter "card" buttons same width?
- [x]  After clicking "Create" in the cluster wizard buttons change their size, it looks strange so it would be nice if that could be fixed but not that important if it's complicated
- [x] Change Deactivated style on text fields, make both border and text 50% opacity on deactivated
- [x] Change Light Theme buttons/primary/secondary colors to `#00A3D9` and `#00CCA7` respectively as well

EDIT: Copy from below:

- [x] can we have the same padding optically on the user menu? so that it matches with the notifs (moved to https://github.com/kubermatic/dashboard-v2/issues/1979)
