### ISSUE TITLE
Dark Mode Fixes and Improvements 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3398]
- [x] Sidebar change background opacity for active items to `.7`
- [x] Change text and icon color of active item to `#66C9FF`
- [x] Change secondary button (the green ones) color to `#00B2B2` hover color to `#009999`
- [x] Make the Search border color the same as the teritary (grey bordered) button border color
- [x] Make the Search icon the same color as the search text
- [x] Loading hourglass icon should be white 
- [x] Can we try changing our classic white - used for texts and icons and everything, to `.85` opacity on dark mode? Too bright whites on dark backgrounds are almost unpleasant, I want to try if we can soften the contrast like that... It might break some stuff because we probably don't have all the locations in mind that the variable is used but we can try and check
- [x] Cluster Create - Change active stepper text color to `#66C9FF`
- [x] Change active input label color to `#66C9FF`
- [x] Please change checkmark tick icon to white
- [x] Admin panel `+` icon in the `Add Datacenter` button and similar buttons should be white
- [x] Change active items in multiple select text color to `#66C9FF` too (in this case Pod Node Selector)
![image](https://user-images.githubusercontent.com/49145827/120294231-49a81f00-c2c6-11eb-99ac-7003df295adb.png)
