### ISSUE TITLE
[v2.18] Pre-Release Procedure

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#3659]
## Pre-Release Procedure
List of steps to execute before proceeding with the release procedure. It mainly consists of
manual tests and visual checks of the Kubermatic Dashboard.

Every assignee should mark their name next to the checks they're willing to work on.

- [x] Validate display all projects switch on the projects view @maciaszczykm 
- [ ] Visual check of theme changes in the user settings (EE only) @floreks - https://github.com/kubermatic/dashboard/issues/3692
- [x] Items per page changes in the user settings @maciaszczykm 
- [ ] Changes of the initial machine deployment replicas in the admin settings
- [ ] Changes of the user project limit in the admin settings
- [ ] Changes of the resource quota in the admin settings
- [ ] Creation, update, check and deletion in the admin settings of the: @imharshita 
  - [ ] Dynamic datacenters
  - [ ] Administrators
  - [ ] Presets
  - [ ] OPA Constraint templates 
  - [ ] OPA Default Constraints (new; to be added to the template)
  - [ ] OPA Allowed Registry (new; to be added to the template)
- [x] API documentation @maciaszczykm 
- [ ] Changelog
- [x] Alibaba provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [ ] ~Initial machine deployment creation~ (cannot be tested because of https://github.com/kubermatic/kubermatic/issues/7789)
  - [ ] ~Manual machine deployment creation~ (cannot be tested because of https://github.com/kubermatic/kubermatic/issues/7789)
  - [ ] ~Machine deployment scaling~ (cannot be tested because of https://github.com/kubermatic/kubermatic/issues/7789)
  - [ ] ~Machine deployment deletion~ (cannot be tested because of https://github.com/kubermatic/kubermatic/issues/7789)
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
  - [x] Connection to Kubernetes Dashboard
- [x] AWS provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
  - [x] Connection to Kubernetes Dashboard
- [x] Azure provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [x] DigitalOcean provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [x] Hetzner provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [x] OpenStack provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [x] Google Cloud provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [x] vSphere provider @maciaszczykm 
  - [x] Cluster creation with SSH key assigned
  - [x] Cluster version upgrade
  - [x] Initial machine deployment creation
  - [x] Manual machine deployment creation
  - [x] Machine deployment scaling
  - [x] Machine deployment deletion
  - [x] Addon creation & deletion
  - [x] RBAC creation & deletion
  - [x] SSH Key management from cluster details
- [ ] External cluster connection - @floreks
- [ ] Cluster Templates (new; to be added to the template) - @floreks - https://github.com/kubermatic/kubermatic/issues/7797
  - [x] Create a new cluster template
  - [x] Create a cluster based on a cluster template and verify if it is the same as expected
  - [x] Use create from template list and from cluster page
  - [x] Delete cluster template
  - [ ] Repeat scenario for at least 5 providers
  - [ ] Check pagination of the templates list
  - [x] Check if SSH keys are saved correctly
- [ ] Metering
  - [ ] Configure metering
  - [ ] Configure metering credentials
  - [ ] Enable/Disable metering
  - [ ] Listing reports
  - [ ] Downloading reports
- [ ] OPA -> documentation is having guide (new; to be added to the template)  @imharshita 
  - [ ] Default constraints in admin panel: make sure that `Applies To` & `On/Off` column is only displayed in ee version
  - [ ] make sure allowed registries view in admin panel is only visible in ee version
  - [x] test opa enabled + enforced options via admin settings
  - [ ] create cluster with opa enabled & verify that `Constraints` + `Gatekeeper` tabs are visible at the bottom of cluster details view
  - [ ] add/edit/delete constraints
  - [ ] add/edit/delete gatekeeper config
- [ ] MLA -> documentation is having guide (new; to be added to the template)
  - [ ] test mla options (user cluster monitoring + user cluster logging) enabled + enforced options via admin settings
  - [ ] create cluster with user cluster monitoring and/or user cluster logging enabled and verify that `Monitoring, Logging & Alerting` tab is visible at the bottom of cluster details view
  - [ ] add/edit/delete rule group
  - [ ] edit/reset alertmanager config

## Not yet testable (add to above steps once merged and ready)
- [ ] Cluster Backups
  - [ ] Creating automatic cluster backup/snapshot
  - [ ] Deleting automatic backups/snapshosts   
  - [ ] Restoring cluster state from snapshot
  - [ ] Information about pending cluster restoration
  - [ ] Automated snapshot creation by automatic cluster backups

## TODO
Remember to update the general template in case the list of tests changes between releases.

**Comment by floreks** [comment]
@kgroschoff @maciaszczykm feel free to extend the list of tests if needed.

**Comment by maciaszczykm** [comment]
I've added few checks for the cluster templates. By the way, we should remember to test features that were implemented by someone else, not us.

**Comment by maciaszczykm** [comment]
I'll transform this into epic to connect all created issue into it.

**Comment by maciaszczykm** [comment]
@kgroschoff @floreks Please put any changes of the template into https://github.com/kubermatic/dashboard/pull/3689.

**Comment by maciaszczykm** [comment]
It can be closed because the release is already done. If you will find any issues just report them.
