### ISSUE TITLE
Import external clusters

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3887]
Add support for importing and managing external clusters from the dashboard. See https://github.com/kubermatic/kubermatic/issues/6414 for more details.

Design: https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI

The highest priority:

- [x] import AKS, EKS and GKE clusters
- [x] display cluster details
- [x] display cluster machine deployments (node pools for native clusters)
- [x] display machine deployment nodes

Update cluster version and replica numbers - this requires handling cluster statuses. It's not designed and implemented and can cause potential risk. Without proper status handling, we will display a lot of errors on the UI page until the cluster is in a ready state. It must be taken into the consideration before the release.

**Comment by maciaszczykm** [comment]
Duplicate of https://github.com/kubermatic/kubermatic/issues/6414.
