### ISSUE TITLE
[v2.19] Pre-Release Procedure

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#4022]
## Pre-Release Procedure
List of steps to execute before proceeding with the release procedure. It mainly consists of
manual tests and visual checks of the Kubermatic Dashboard.

Every assignee should mark their name next to the checks or groups they're willing to work on.

### User Settings (@floreks)
- [x] Check using two browser windows if settings are successfully saved and loaded
- [x] Check all available themes (in enterprise edition)
- [x] Check different items per page options across the application
- [x] Check default project switch functionality

### Admin Settings (@floreks)
- [x] Check if admin settings are available to administrators only
- [x] Check using two browser windows if default and interface settings are successfully saved and loaded
- [x] Check "Default and Limits" options
- [x] Check "Interface" options
- [x] Check "Accounts" list information
- [x] Check "Backup destinations" configuration and usage
- [x] Check operations like create, list, update and delete of dynamic datacenters
- [x] Check operations like create, list, update and delete of provider presets
- [x] Check operations like create, list and delete of administrators

### Metering
- [x] Check metering configuration
- [x] Check metering credentials configuration
- [x] Check enabling and disabling metering
- [x] Check listing reports
- [x] Check downloading reports

### OPA (@kgroschoff)
- [x] Check if `Applies To` and `On/Off` columns are available only in enterprise edition in the default constraints list
- [x] Check if allowed registries view is available only in enterprise edition
- [x] Check options to enable and enforce OPA from the admin settings
- [x] Check if `Constraints` and `Gatekeeper` tabs are visible in the cluster details if OPA was enabled
- [x] Check operations like create, list, update and delete of constraints
- [x] Check operations like create, list, update and delete of Gatekeeper config

### MLA (@maciaszczykm)
- [x] Check options to enable and enforce MLA from the admin settings
- [x] Check if `Monitoring, Logging & Alerting` tab is visible in the cluster details if MLA was enabled
- [x] Check operations like create, list, update and delete of rule groups
- [x] Check operations like update and reset of Alertmanager config

### Projects (@maciaszczykm)
- [x] Check operations like create, list, update and delete
- [x] Check pagination, filtering and sorting
- [x] Check switch between list and cards view
- [x] Check switch to show all project

### Clusters (@floreks)
- [x] Check SSH key management from cluster details
- [x] Check RBAC management from cluster details
- [x] Check addon management from cluster details
- [x] Check connection to Kubernetes Dashboard from cluster details

### External Clusters (@floreks)
- [x] Check external cluster Import/Connect functionality for all supported providers
- [x] Check external cluster details and machine deployment details
- [x] Check cluster version upgrades (for the supported providers)
- [x] Check machine deployment scaling
- [x] Check external cluster disconnect functionality

### Cluster Templates (@kgroschoff)
- [x] Check creation of cluster templates with SSH key in the project scope and verify it was saved 
- [x] Check creation of cluster templates in the user scope and verify it was saved
- [x] Check creation of cluster templates in the global scope and verify it was saved
- [x] Check cluster creation from the templates created before and verify if it is the same as expected
- [x] Check cluster creation from the cluster template list and from the clusters list
- [x] Check cluster template deletion
- [x] Check cluster template management for at least 3 most common providers
- [x] Check pagination, search and filtering

### Backups
- [x] Check create and delete of automatic cluster backup/snapshot
- [x] Check restore from snapshot
- [x] Check if information about pending cluster restoration is available
- [x] Check automated snapshot creation by automatic cluster backups

### Providers
- [x] Alibaba (@floreks)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] AWS (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] Azure (@floreks)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] DigitalOcean (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] GCP (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] Hetzner (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] OpenStack (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] KubeVirt (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] Equinix Metal (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion
- [x] vSphere (@maciaszczykm)
  - [x] Check cluster creation with SSH key assigned
  - [x] Check initial machine deployment creation
  - [x] Check manual machine deployment creation with different operating systems
  - [x] Check cluster version upgrades
  - [x] Check machine deployment scaling
  - [x] Check machine deployment deletion
  - [x] Check cluster deletion

### Other Features (@maciaszczykm)
- [x] Check the changelog
- [x] Check the API documentation
- [x] Check the terms of service
- [x] Check if all provider logos are up-to-date
- [x] Visual checks of any UI related issues (padding, colors, overlapping elements, etc.)
