### ISSUE TITLE
KubeOne Import

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4446]
Kubeone Import includes:
- [x] import: view the cluster
- [x] upgrade: upgrading the cluster version
- [x] migrate container runtime

[KubeOne Create Draft](https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=6516%3A54056)
