### ISSUE TITLE
Dark Mode and other UI/UX Fixes

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4637]
### Cluster dropdown, project overview, and header menu, provider preset (admin panel), addon (on cluster view) dropdowns:

- [x] Change to  `#363636` dropdown background color 
- [x] Change to `#484848` hover item background color
- [x] Disabled text color: `#7c7c7c` (for example when cluster is starting up -> cluster dropdown items)

### Icon Color Changes
- [x] back arrow should be white (cluster overview, MDs, etc Backups, admin panel -> metering, ...) 
- [x] etcd Backups, Snapshots, Restores trashbin icon should be white
- [x] Members edit and delete icon should be white
- [x] lighten loading spinner to `#7e868f`  (or a similar shade) (for example on cluster view additional cluster information)

### Disabled & Validation Changes
- [x] on cluster delete with enforced settings, disabled text color: `#7c7c7c`
- [x] missing validation for "Create cluster from template" (I can enter "aaa" or something and go to next step, there's no template by that name)
- [x] "Create cluster from template" should be disabled if there's no template available

## Universal
- [x] On MDs when opening/closing the Event card the icon and text "x events" jumps left/right 
- [x] Own projects should be first in project dropdown in header
- [x] Headline inside the project dropdown should be styled as shown here
![dropdown](https://user-images.githubusercontent.com/49145827/176654485-2bc22dc3-17fa-457f-b7ce-fd8057d69ebc.PNG)
- [x] the vertical space between for example Cluster ID label and the ID and SSH Keys label and the key are different, it should be like Cluster ID for all (issue already exists here #4493) 
![image](https://user-images.githubusercontent.com/49145827/176656359-59ac7aaf-fd72-44f4-a373-7231bc19ad18.png)

- [x] Add separator lines to dropdown 
![image](https://user-images.githubusercontent.com/49145827/176845511-2cfe0c0e-b606-4e4d-a7ad-ec31764de0b0.png)
- [x] Add separator line above sign out 
 ![image](https://user-images.githubusercontent.com/49145827/176852043-a77fd20c-9841-4461-a336-1d9452ec0125.png)

- [x]  On hover of Member card/Member headline add arrow, make arrow and headline link to Member page
![image](https://user-images.githubusercontent.com/49145827/176845949-3bb40a0b-7f16-476a-8d43-d796fb781911.png)

### Opinion Requested
- [ ] Cluster Template Wizard should end only with "Create Template" option" not with "create cluster" option. Alternatively we can prove the option: "Create cluster and Cluster Template"  
- [x] Change Delete Cluster Template dialogue "persist." to "stay." or "remain." (more commonly used words)

**Comment by Waseem826** [comment]
>Cluster Template Wizard should end only with "Create Template" option" not with "create cluster" option. Alternatively we can prove the option: "Create cluster and Cluster Template"

@cschieder I think its fine to display separate buttons for creating template and cluster because user can choose between any of them. If we only display "Create Template" then we're adding an extra step to create the cluster. WDYT?

**Comment by Waseem826** [comment]
>the vertical space between for example Cluster ID label and the ID and SSH Keys label and the key are different, it should be like Cluster ID for all.

I have created separate [issue](https://github.com/kubermatic/dashboard/issues/5024) for this task since it requires some extra effort and we might also need to change the implementation.

**Comment by cschieder** [comment]
@Waseem826 I'm not sure about this because if you click on "create cluster template" creating the template is your primary action, yet on the last page of the wizard the primary action optically is "Create Cluster" just like in normal wizard

Also, you cannot create multiple clusters from the last wizard page, so it feels odd to save template and then create 1 cluster when you wanted more than 1 from the template

And another thing. Saving the template does not close the wizard but it is the primary action of this entire userflow. 

These are my concerns with the current state, so we could make "Create Cluster and Template" a thing, Maybe even allow in this case to save the template and immediately open the "Create clusters from template" dialog, that way the user can create however many clusters they want from the template they just created and both "Save template" and "Create Template and Cluster" would finish the user flow and send the user back to Cluster Template table page

Thoughts?

**Comment by Waseem826** [comment]
I agree with your concerns and I think we can swap the primary action of wizard in this case and also when user saves the template we can close the wizard and open create cluster from template dialog. 
However, this will require some extra work so I think its better if we create a separate issue for this. Can you please create that if you agree?

**Comment by cschieder** [comment]
Done, #5026
