### ISSUE TITLE
Cluster Wizard Summary, remove nested columns 

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5112]
### Tasks

- [x] Remove nested columns
- [x] move data/items into one line 
- [x] Adjust style of subheadlines (16, capital letters) 
- [x] Fix vertical and horizontal centering of numbers next to headlines 
- [x] Break 2 column style into 1 column at 350px min column width 
- [x] ![image](https://user-images.githubusercontent.com/49145827/197163420-071c4ca8-a219-4dc7-895f-7bf33bde99e3.png)
- [x] Remove additional spacing between Applications and application cards
- [x] Increase spacing between end of one section/point and the beginning of the next (60px in design file right now) 

https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=7732%3A85142
![Cluster_Create_5_Summary-redesign test](https://user-images.githubusercontent.com/49145827/197162838-67a7db5b-55f5-44a7-903f-3a04175d1d31.png)

Comparison
![image](https://user-images.githubusercontent.com/49145827/197162756-423a38ad-00f0-48d6-af99-24cc9535cc14.png)
