### ISSUE TITLE
KubeVirt Wizard Changes

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5283]
### Modal
![image](https://user-images.githubusercontent.com/49145827/202137955-c63aca55-c66c-4d03-85e8-31733c2a0410.png)
### On Page (Table and Dropdown)
![image](https://user-images.githubusercontent.com/49145827/202704416-5f77bd97-3d7f-44b0-93bb-d37acacd24b5.png)
### On Page, Empty 
![image](https://user-images.githubusercontent.com/49145827/202139152-d1955779-51b7-4422-af5f-fc24bef6f341.png)

## Tasks
- [x] Rename `Custom Local Disks` to `Custom Images`
- [x] Move Custom Images to Initial Nodes Page (Step 4)
- [x] Add Operating System Type dropdown on modal 
- [x] Change custom image creation to work via modal (like applications do)
- [x] Reuse the table we use for custom images on the summary for the initial nodes page 
- [x] Add edit and delete options to the table (edit reopens modal with save changes confirm button instead of add button) 
- [x] Replace URL with OS type on table  (we will omit the URL from the table because it takes too much space, the user can look it up again via edit if needed) (this only applies to the initial nodes page, on the summary the URL column stays, see last point)
- [ ] Operating System Image dropdown will get two categories
Standard Images and Custom Images (aka the ones that were defined above, if none is defined, this category is hidden completely) 
- [x] Operating System Image dropdown will be renamed after selecting an OS (left side), the dropdown will be renamed based on the OS to show that the dialog is filtered to only show OS Images of the correct type. Example: User selects Ubuntu, dropdown is renamed to "Ubuntu Systems Image", the dropdown shows only Images that work with Ubuntu) 
- [x] On summary page only the "URL" column _will not_ be changed to "OS" and remaine "URL" because the OS is already visible there and it would be redundant 
- [x] Show custom images only if flag `kubevirt.images.enableCustomImages` on seed config is set

**Comment by mfranczy** [comment]
The design looks great.

Additionaly (this doesn't force the design change), when user creates a new custom image and choose a storage class for it, and later the user selects the custom image from drop down list the previously storage class should be set as a default (although users should be able to change it).

@sankalp-r please take a look as well link the issues you worked on.

**Comment by mfranczy** [comment]
@shaase-ctrl I think we should make custom images feature ee only as well, what do you think?
Then from KubeVirt side we would have two ee in context of disks:
* caching disks
* custom images for users

**Comment by mfranczy** [comment]
We have decided to use custom images only as EE and that should not be visible on CE.
Information if we should show user custom images (the wizard and each view related) have to be read from seed configuration `kubevirt.images.enableCustomImages: [true|false]`

**Comment by mfranczy** [comment]
@Waseem826 I should be able to finish the API at the beginning of next week.

**Comment by Waseem826** [comment]
As discussed with @csengerszabo and @mfranczy we'll skip this issue from `2.22` release so I've updated the labels accordingly.
