### ISSUE TITLE
Modify Project Overview

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#5323]
### Tasks

- [x] Remove tab styling from Cluster Distribution (we haven't implemented #4467 for a while now, we can style it like a tabbed card again once it actually behaves like tabbed cards)
- [x] Add labels 
- [x] Cut off labels after reaching end of the line
- [x] Add unfold functionality to labels
- [x] Reduce labels on project table to just show a counter 
![image](https://user-images.githubusercontent.com/49145827/203512734-1781af5c-d8fc-4b70-aaf4-effc1a602d47.png)
- [x] (conditional on sidebar changes going live) Change button to link to Members subpoint of access and remove '& Groups' part

### Design
![image](https://user-images.githubusercontent.com/49145827/203512006-58bcbfdd-597b-4945-8b9e-01eeb7c67052.png)
