### ISSUE TITLE
Migrate Angular Material components to version 15

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5864]
Angular was upgraded to version 15 in https://github.com/kubermatic/dashboard/issues/5335. However, Angular Material components were not migrated since it required extra effort and could've caused breaking changes.
So as part of this epic we should migrate each Angular Material component individually from legacy to v15 by following instructions in https://github.com/angular/components/blob/main/guides/v15-mdc-migration.md.

```[tasklist]
### Tasks
- [ ] Button >> ahmad
- [ ] Input >> ahmad
- [ ] List  >> ahmad
- [x] Progress Spinner ~ https://github.com/kubermatic/dashboard/pull/6002
- [x] Tooltip https://github.com/kubermatic/dashboard/pull/6673#event-12652893132
- [x] Select https://github.com/kubermatic/dashboard/pull/6673#event-12652893132
- [ ] Autocomplete >> ahmad
- [x] Checkbox ~ https://github.com/kubermatic/dashboard/pull/6642#event-12307803612
- [x] Menu ~ no changes required
- [x] Chips ~ https://github.com/kubermatic/dashboard/pull/6655#issuecomment-2057438748
- [x] Card ~ https://github.com/kubermatic/dashboard/pull/6655#issuecomment-2057438748
- [ ] https://github.com/kubermatic/dashboard/issues/5921
- [x] Slider ~ https://github.com/kubermatic/dashboard/pull/6142
- [x] Slide Toggle ~ https://github.com/kubermatic/dashboard/pull/6142
- [x] Progress Bar ~ https://github.com/kubermatic/dashboard/pull/6002
- [ ] Table >> ahmad
- [ ] Tabs >> ahmad
- [x] Option https://github.com/kubermatic/dashboard/pull/6673#event-12652893132
- [x] Form Field https://github.com/kubermatic/dashboard/pull/6673#event-12652893132
- [x] Paginator ~ https://github.com/kubermatic/dashboard/pull/6140
- [ ] https://github.com/kubermatic/dashboard/pull/5993
- [x] Radio ~ https://github.com/kubermatic/dashboard/pull/6640
```

After migration, make sure that all overridden CSS styles are also updated and work as expected.

**Comment by ahmedwaleedmalik** [comment]
https://github.com/kubermatic/dashboard/pull/6629 takes care of migrations but we still need to refactor, fix the components a bit. Let's do that one by one.

Also, the unit tests need to be fixed against this ticket as they were marked as optional in https://github.com/kubermatic/dashboard/pull/6629
