### ISSUE TITLE
UI-Testing - Release 2.23

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#5986]
This contains UI testing tickets for Release 2.23.

```[tasklist]
### Testing Issues
- [ ] https://github.com/kubermatic/dashboard/issues/5955
- [ ] https://github.com/kubermatic/dashboard/issues/5985
- [ ] https://github.com/kubermatic/dashboard/issues/5990
- [ ] https://github.com/kubermatic/dashboard/issues/5991
- [ ] https://github.com/kubermatic/dashboard/issues/5992
- [ ] https://github.com/kubermatic/dashboard/issues/6008
- [ ] https://github.com/kubermatic/dashboard/issues/6014
- [ ] https://github.com/kubermatic/dashboard/issues/6018
- [ ] https://github.com/kubermatic/dashboard/issues/6019
- [ ] https://github.com/kubermatic/dashboard/issues/6020
- [ ] https://github.com/kubermatic/dashboard/issues/6021
- [ ] https://github.com/kubermatic/dashboard/issues/6022
- [ ] https://github.com/kubermatic/dashboard/issues/6023
- [ ] https://github.com/kubermatic/dashboard/issues/6024
- [ ] https://github.com/kubermatic/dashboard/issues/6027
- [ ] https://github.com/kubermatic/dashboard/issues/6034
```

**Comment by ahmedwaleedmalik** [comment]
This is complete now.
