### ISSUE TITLE
Test External Clusters - Test Release 2.23

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6014]
Test import and create external clusters functionality. Also make sure that cluster details and MD details page work as expected.

```[tasklist]
### Tasks
- [x] Test AKS provider
- [ ] Test GKE provider
- [ ] Test EKS provider
```
