### ISSUE TITLE
UI-Testing - Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6285]
```[tasklist]
### Testing Issues
- [ ] https://github.com/kubermatic/dashboard/issues/6257
- [ ] https://github.com/kubermatic/dashboard/issues/6298
- [ ] https://github.com/kubermatic/dashboard/issues/6299
- [ ] https://github.com/kubermatic/dashboard/issues/6300
- [ ] https://github.com/kubermatic/dashboard/issues/6301
- [ ] https://github.com/kubermatic/dashboard/issues/6302
- [ ] https://github.com/kubermatic/dashboard/issues/6306
- [ ] https://github.com/kubermatic/dashboard/issues/6307
- [ ] https://github.com/kubermatic/dashboard/issues/6308
- [ ] https://github.com/kubermatic/dashboard/issues/6309
- [ ] https://github.com/kubermatic/dashboard/issues/6310
- [ ] https://github.com/kubermatic/dashboard/issues/6311
- [ ] https://github.com/kubermatic/dashboard/issues/6312
- [ ] https://github.com/kubermatic/dashboard/issues/6313
- [ ] https://github.com/kubermatic/dashboard/issues/6314
```
