### ISSUE TITLE
Test External Clusters - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6308]
Test import and create external clusters functionality. Also make sure that cluster details and MD details page work as expected.

```[tasklist]
### Tasks
- [x] Test AKS provider
- [x] Test GKE provider
- [x] Test EKS provider
```

**Comment by ahmadhamzh** [comment]
## EKS
* it look like any imported clusters would have this error `Error: Can't access cluster via kubeconfig,error: the server has asked for the client to provide credentials` except if the external cluster you import it already been create from our dashboard then it can imported correctly. 

![image](https://github.com/kubermatic/dashboard/assets/85109141/91137e24-8e0a-4095-9ce6-5b5b9eb3d39e)

* the list of k8s versions don't have the 1.28 version.

![image](https://github.com/kubermatic/dashboard/assets/85109141/de61e7d9-c5b7-4027-9ad7-a1d892134e2a)

* Error `unable to list: default because of unknown namespace for the cache` keep coming it seems like when we create a cluster from our dashboard the EKS cluster created without any namespaces. 

![image](https://github.com/kubermatic/dashboard/assets/85109141/8de33a1a-e077-4de1-914a-be1a1be9b107)

* on edit MD the value to update the version must not have the patch release value (e.g 1.27.0 will not work wich is how we do it now, it must be 1.27).
* when you try to delete the cluster while we have a nodegroup we get a warning that we need to delete the Nodegroup first, so it would be better if we keep the delete button disabled 
![image](https://github.com/kubermatic/dashboard/assets/85109141/86bf46ef-986d-4431-8083-f2c0aa7f5360)

**Comment by ahmadhamzh** [comment]
## GKE
* the service account credentials have a note that it have to be base64 but actually even if add the service account as base64 the field validation shows an error but if i create a preset and i add the service account ( not in base64) it worked 

![image](https://github.com/kubermatic/dashboard/assets/85109141/3ae49e40-564f-47f3-ad2f-dd96d24b811b)

* import only work for gke clusters that been created from the dashboard, if you create a gke cluster from the provider side and then try to import it i get error ` 'zone' field cannot be used to access GKE regional clusters. Use 'name' field instead` .

![image](https://github.com/kubermatic/dashboard/assets/85109141/2751328e-d300-4196-b632-e9dbaa6128f2)

* Error unable to list: default because of unknown namespace for the cache keep coming it seems like when we create a cluster from our dashboard the EKS cluster created without any namespaces.

![image](https://github.com/kubermatic/dashboard/assets/85109141/94514e3c-87be-42b5-b5b2-a336d56d00dc)

**Comment by ahmadhamzh** [comment]
## AKS

* in the add machine deployment dialog the `add machine deployment`  button become enable before the `vm sizes` been selected, so if you try to add the machine deployment the request will fail.

![image](https://github.com/kubermatic/dashboard/assets/85109141/ef494f03-0c0d-47bd-9978-1c3be62768e8)

**Comment by xrstf** [comment]
I'm taking a look at these errors.

**Comment by ahmadhamzh** [comment]
the only remaining issue is tracked by this ticket : https://github.com/kubermatic/dashboard/issues/6332
