### ISSUE TITLE
Test KKP Dashboard UI

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6534]
This epic includes all testing tasks related to the KKP dashboard UI.

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/dashboard/issues/6530
- [ ] https://github.com/kubermatic/dashboard/issues/6529
- [ ] https://github.com/kubermatic/dashboard/issues/6528
- [ ] https://github.com/kubermatic/dashboard/issues/6512
- [ ] https://github.com/kubermatic/dashboard/issues/6491
- [ ] https://github.com/kubermatic/dashboard/issues/6483
- [ ] https://github.com/kubermatic/dashboard/issues/6479 
- [ ] https://github.com/kubermatic/dashboard/issues/6536
- [ ] https://github.com/kubermatic/dashboard/issues/6537
- [ ] https://github.com/kubermatic/dashboard/issues/6544
- [ ] https://github.com/kubermatic/dashboard/issues/6556
- [ ] https://github.com/kubermatic/dashboard/issues/6557
- [ ] https://github.com/kubermatic/dashboard/issues/6558
- [ ] https://github.com/kubermatic/dashboard/issues/6559
- [ ] https://github.com/kubermatic/dashboard/issues/6560
- [ ] https://github.com/kubermatic/dashboard/issues/6565
- [ ] https://github.com/kubermatic/dashboard/issues/6568
```
