### ISSUE TITLE
Applications - Test Release 2.25

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6565]
Test Application Installations after latest changes to the values and default values fields.

## Testing Procedure

```[tasklist]
### Tasks
- [x] Application Definitions are loaded along with default values in Add Application Dialog.
- [ ] Applications are saved (along with `valuesBlock` field) during cluster creation and saving cluster templates.
- [ ] Applications can be added from cluster details page.
- [ ] Applications can be edited from cluster details page.
```

**Comment by Waseem826** [comment]
There is still one issue (https://github.com/kubermatic/dashboard/pull/6562#issuecomment-1968621786) pending before this can be tested.

**Comment by ahmedwaleedmalik** [comment]
@Waseem826 what's left for this ticket?

**Comment by Waseem826** [comment]
From my side, we just need to test https://github.com/kubermatic/dashboard/pull/6591.

**Comment by ahmedwaleedmalik** [comment]
> From my side, we just need to test #6591.

Can you please test that on dev and then close this ticket if that works?

**Comment by ahmedwaleedmalik** [comment]
![Screenshot 2024-03-11 at 14 27 45](https://github.com/kubermatic/dashboard/assets/18264334/8a1bcfe2-eb9d-4c68-931c-bd59de9fa013)

Just tested this and it works fine 👍
