### ISSUE TITLE
Test KKP Dashboard - Test Release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6811]
This epic keeps track of the tickets to be tested for KKP 2.26.0.

```[tasklist]
### Testing Tickets
- [ ] https://github.com/kubermatic/dashboard/issues/6806
- [ ] https://github.com/kubermatic/dashboard/issues/6788
- [ ] https://github.com/kubermatic/dashboard/issues/6785
- [ ] https://github.com/kubermatic/dashboard/issues/6776
- [ ] https://github.com/kubermatic/dashboard/issues/6775
- [ ] https://github.com/kubermatic/dashboard/issues/6820
- [ ] https://github.com/kubermatic/dashboard/issues/6821
- [ ] https://github.com/kubermatic/dashboard/issues/6822
- [ ] https://github.com/kubermatic/dashboard/issues/6823
- [ ] https://github.com/kubermatic/dashboard/issues/6824
- [ ] https://github.com/kubermatic/dashboard/issues/6825
- [ ] https://github.com/kubermatic/dashboard/issues/6826
- [ ] https://github.com/kubermatic/dashboard/issues/6827
- [ ] https://github.com/kubermatic/dashboard/issues/6831
- [ ] https://github.com/kubermatic/dashboard/issues/6798
- [ ] https://github.com/kubermatic/dashboard/issues/6832
- [ ] https://github.com/kubermatic/dashboard/issues/6842
- [ ] https://github.com/kubermatic/dashboard/issues/6841
- [ ] https://github.com/kubermatic/dashboard/issues/6861
```
