### ISSUE TITLE
Applications - Test Release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6820]
Test Application Installation.

## Testing Procedure

```[tasklist]
### Tasks
- [x] Application Definitions are loaded along with default values in Add Application Dialog.
- [x] Applications are saved (along with `valuesBlock` field) during cluster creation and saving cluster templates.
- [x] Applications can be added from cluster details page.
- [x] Applications can be edited from cluster details page.
```

**Comment by ahmadhamzh** [comment]
all working as expected
