### ISSUE TITLE
Cluster Backup - Test release 2.26

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#6826]
Test Cluster Backups/Schedule/Restore.

```[tasklist]
### Tasks
- [x] Only clusters that have the cluster backup feature are shown in the clusters list.
- [x] Items that are shown in the table belong to the same selected cluster.
- [x] Create Backup/Schedule/Restore and check if the status is running.
- [x] Test delete one, delete selected.
- [x] Download the backup files from the download button in the actions column.
```

**Comment by ahmedwaleedmalik** [comment]
It works similar to how it worked in KKP 2.25 so we can close this testing ticket. But we have A LOT of issues in there that need to be improved, created https://github.com/kubermatic/dashboard/issues/6864 for that.

**Comment by ahmedwaleedmalik** [comment]
Needs to be re-tested after https://github.com/kubermatic/dashboard/pull/6866

**Comment by ahmedwaleedmalik** [comment]
new changes look good
