### ISSUE TITLE
Use node deployments instead of nodes

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#872]
This is a frontend part of https://github.com/kubermatic/kubermatic/issues/2099:

>* [x] Show machineDeployments
>* [x] Discuss and implement how a machineDeployments status can be displayed
>  * [ ]   Do we want to show individual machineSets and their configuration?
>* [x] Allow updating machineDeployments
>* [x] Continue to show machines and allow deleting them, but not creation of new ones
>  * [x] Maybe implement this in a backwards-compatible way by checking if the API exposes the machineDeployment endpoint?

- [x] Design machine deployment view #867
- [x] Create node deployments instead of nodes #869
- [x] List node deployments in cluster details #870
- [x] Add option to update node deployments #873
- [x] Add option to delete node deployments #871
- [x] Should we have an endpoint to list nodes belonging to node deployment (like in mockups)?
- [x] Do we need to do anything with GET endpoint?
