### ISSUE TITLE
Isolate e2e tests

### ISSUE THREAD

**Issue by floreks** [kubermatic/dashboard#975]
E2E tests should be isolated and started in a clean environment every time to avoid flakes when multiple test instances are run in parallel.

Acceptance criteria
 - [x] Be able to start a `kind` cluster inside a Pod container on dev (related issue https://github.com/kubernetes-sigs/kind/issues/136#issuecomment-460655628)
 - [x] Install Kubermatic inside the `kind` cluster (api, ui, controller, dex)
 - [x] Expose API/UI/DEX to the pod running the `kind` cluster
 - [x] Create a `NodePort` service utilizing [nodeport-proxy](https://github.com/kubermatic/nodeport-proxy) functionality to dynamically expose user clusters to the outside.
 - [x] Configure and run e2e tests against created environment
 - [x] Make sure there are no dependencies on external environments (i.e. `dev.kubermatic.io`)
